### ISSUE TITLE
Sphinx padding bug

### ISSUE THREAD

**Issue by david415** [sphinx-cryptography/rust-sphinxcrypto#6]
According to the recently submitted paper: Breaking and (Partially) Fixing Provably Secure Onion Routing, ( https://arxiv.org/abs/1910.13772 ) there is a padding bug where a sphinx implementation creates a header and in so doing uses zeros to pad the beta field whereas random data should be used instead because of the use of the stream cipher...

https://github.com/UCL-InfoSec/sphinx/blob/c05b7034eaffd8f98454e0619b0b1548a9fa0f42/SphinxClient.py#L67

```
# The os.urandom used to be a string of 0x00 bytes, but that's wrong
beta = dest + id + os.urandom(((2 * (p.r - nu) + 2)*p.k - len(dest)))
beta = p.xor(beta,
p.rho(p.hrho(asbtuples[nu-1]['s']))[:(2*(p.r-nu)+3)*p.k]) + phi
```

This bug, that is, if beta were padded with zeros instead of random bytes would allow
an adversary to determine the length of the route.

**Comment by burdges** [comment]
It appears the concern is hiding the route length from an exit provider to whom the message reveals all the intermediate secrets, yes?  It's not a concern if sphinx is used end-to-end, although the security proof for that setting remains broken.  

I'd noticed schetchiness in the wrap-resistance section of the sphinx paper, but I'd always assumed the real fix required using Rogaway's new game-based tricks.  It's interesting they kinda managed to fix the UC proof, although this fix breaks replies.
